databases:
  - name: keio_goclub_homepage_DB
    databaseName: keio_goclub_homepage_db
    user: keio_goclub_homepage
    region: singapore

services:
  - type: web
    name: keio_goclub_homepage
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: keio_goclub_homepage_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
